[package]
name = "ui"
version = "0.1.0"
authors = ["janmeischner"]
edition = "2018"

[dependencies]
types = { path = "../types" }
config = { path = "../config" }
ansi_term = "^0.11.0"
dialoguer = "^0.3.0"