[package]
name = "ui"
version = "0.1.0"
authors = ["janmeischner"]
edition = "2018"

[dependencies]
types = { path = "../types" }
todofilter = { path = "../todofilter" }
ansi_term = "^0.11.0"
dialoguer = "^0.7.1"
console = "^0.13.0"
log = "^0.4.6"
