[package]
name = "ui"
version = "0.1.0"
authors = ["janmeischner"]
edition = "2018"

[dependencies]
types = { path = "../types" }
todofilter = { path = "../todofilter" }
ansi_term = "^0.11.0"
dialoguer = "^0.3.0"
console = "^0.7.7"
log = "^0.4.6"