name: Build New Version
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.todoco/**'
      - '.todocoignore'
      - '**/*.md'
      - 'todoco.*'

# Todo: Decide For new version use cargo login $CRATES_IO_TOKEN and cargo publish
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install Minimal Rust Version
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
        override: true
    - name: Execute Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: Build todoco Artifact
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --release --package todoco

    #### UPLOAD ARTIFACTS ####
    - name: Upload Mac Artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'macOS-latest'
      with:
        name: todoco.mac
        path: ./target/release/todoco
    - name: Upload Ubuntu Artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        name: todoco.ubuntu
        path: ./target/release/todoco
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'windows-latest'
      with:
        name: todoco.windows
        path: ./target/release/todoco.exe
