name: Test And Build
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    env:
      PATH: "$PATH:$HOME/.cargo/bin"
    steps:
    - name: Install cargo
      if: matrix.os == 'macOS-latest'
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y && echo "::add-path::${HOME}/.cargo/bin"
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
    - name: Run build
      run: cargo build --verbose
