name: Test And Build
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
          command: build
          args: --release --package todoco
          toolchain: stable
    # For new version use cargo login $CRATES_IO_TOKEN and cargo publish
    - uses: actions/upload-artifact@v1
      with:
        name: todoco
        path: $GITHUB_WORKSPACE/target/release/todoco
