name: Rust
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
 
    steps:
    - uses: actions/checkout@v1
    - name: Run build
      runt: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
